# Generated by Django 4.2.16 on 2024-11-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('resident', models.BooleanField(default=True)),
            ],
        ),
    ]